name: Deploy Hugo site

on:
  push:
    branches:
      - setup-v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.SSH_KEY_GITHUB_IO }}
          external_repository: Devoxx4Kids-NPO/Devoxx4Kids-NPO.github.io
          publish_branch: setup-v2
          publish_dir: ./public
          destination_dir: test
